### ISSUE TITLE
Failed to retrieve daylight cycle

### ISSUE THREAD

**Issue by Tuurlijk** [PaleoCrafter/Chronomorph#10]
```
Failed to retrieve daylight cycle data at 52.38, 4.9 on 2020-11-07!

java.net.UnknownHostException: api.sunrise-sunset.org
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:606)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:376)
	at io.paleocrafter.chronomorph.DaylightCycle$getCycleSync$1.process(DaylightCycle.kt:61)
	at io.paleocrafter.chronomorph.DaylightCycle$getCycleSync$1.process(DaylightCycle.kt:26)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at io.paleocrafter.chronomorph.DaylightCycle.getCycleSync(DaylightCycle.kt:59)
	at io.paleocrafter.chronomorph.DaylightCycle.access$getCycleSync(DaylightCycle.kt:26)
	at io.paleocrafter.chronomorph.DaylightCycle$getCycle$1.call(DaylightCycle.kt:45)
	at io.paleocrafter.chronomorph.DaylightCycle$getCycle$1.call(DaylightCycle.kt:26)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Occurred 2 times today 07:29 GMT+1

Happens about each switch I think. Theme and color switch seem to work though.

**Comment by marvin-roesch** [comment]
This has been fixed since I switched to using a library for calculating the sunrise/sunset times instead of that API.
