### ISSUE TITLE
theme changes, but colorscheme does not

### ISSUE THREAD

**Issue by Tuurlijk** [PaleoCrafter/Chronomorph#11]
The error is:
```
Details: Current thread: Thread[ApplicationImpl pooled thread 730,4,Idea Thread Group] 872232045
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1354388860

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.openapi.editor.impl.EditorImpl.assertReadAccess(EditorImpl.java:3295)
	at com.intellij.openapi.editor.impl.EditorImpl.getSettings(EditorImpl.java:917)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.isLineMarkersShown(EditorGutterComponentImpl.java:1488)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.getLineMarkerAreaWidth(EditorGutterComponentImpl.java:1534)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.sizeHash(EditorGutterComponentImpl.java:790)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.updateSize(EditorGutterComponentImpl.java:773)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.reinitSettings(EditorGutterComponentImpl.java:304)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.updateUI(EditorGutterComponentImpl.java:300)
	at com.intellij.util.IJSwingUtilities.updateComponentTreeUI(IJSwingUtilities.java:94)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:1095)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.java:849)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.handleCurrentSchemeSwitched(EditorColorsManagerImpl.java:168)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:157)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.onCurrentSchemeSwitched(EditorColorsManagerImpl.java:113)
	at com.intellij.configurationStore.schemeManager.SchemeManagerBase.setCurrent(SchemeManagerBase.kt:35)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.setGlobalScheme(EditorColorsManagerImpl.java:470)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateEditorSchemeIfNecessary(LafManagerImpl.java:809)
	at com.intellij.ide.ui.laf.LafManagerImpl.setLookAndFeelImpl(LafManagerImpl.java:621)
	at com.intellij.ide.ui.laf.LafManagerImpl.setCurrentLookAndFeel(LafManagerImpl.java:593)
	at com.intellij.ide.ui.LafManager.setCurrentLookAndFeel(LafManager.java:41)
	at com.intellij.ide.actions.QuickChangeLookAndFeel.switchLafAndUpdateUI(QuickChangeLookAndFeel.java:96)
	at io.paleocrafter.chronomorph.Chronomorph$applyEntry$1.invoke(Chronomorph.kt:87)
	at io.paleocrafter.chronomorph.Chronomorph$applyEntry$1.invoke(Chronomorph.kt:23)
	at io.paleocrafter.chronomorph.Chronomorph.runOrSchedule(Chronomorph.kt:99)
	at io.paleocrafter.chronomorph.Chronomorph.applyEntry(Chronomorph.kt:86)
	at io.paleocrafter.chronomorph.Chronomorph.check(Chronomorph.kt:53)
	at io.paleocrafter.chronomorph.Chronomorph.check(Chronomorph.kt:42)
	at io.paleocrafter.chronomorph.Chronomorph$1.invoke(Chronomorph.kt:30)
	at io.paleocrafter.chronomorph.Chronomorph$1.invoke(Chronomorph.kt:23)
	at io.paleocrafter.chronomorph.Chronomorph$sam$java_lang_Runnable$0.run(Chronomorph.kt)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

PhpStorm 2021.1.1
Build #PS-211.7036.8, built on April 15, 2021
Licensed to Michiel Roos
Subscription is active until December 5, 2021.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-7612-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.tree.collapse.recursively=false, ide.tooltip.initialDelay=506
Non-Bundled Plugins: Scratch (1.10), Shifter (1.9.6), com.4lex4.intellij.solarized (2.3.0), com.intellij.ideolog (203.0.27.0), de.onigunn.intellij.xliff (0.2.0), io.paleocrafter.chronomorph (2020.1-1.0.2), net.seesharpsoft.intellij.plugins.file-preview (1.6.4), org.intellij.RegexpTester (1.0.8), mobi.hsz.idea.gitignore (4.1.0), org.toml.lang (0.2.145.3797-211), some.awesome (1.14), de.espend.idea.laravel (0.15.4), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), com.ptby.dynamicreturntypeplugin (2.0.12), de.espend.idea.php.annotation (8.0.0), de.sgalinski.fluid.plugin.id (2.4.0), de.sgalinski.typoscript.enterprise.plugin.id (2.4.0), com.cedricziel.idea.typo3 (211.7.1), lv.midiana.misc.phpstorm-plugins.deep-keys (2021.03.26.001), ru.adelf.idea.dotenv (2021.1)
Current Desktop: pop:GNOME

**Comment by marvin-roesch** [comment]
Sorry for getting to this so late, @Tuurlijk, 2021.1 appears to have introduced some changes to themes and color schemes that made the theme-default color scheme always override the one that I explicitly set. I also made a dumb mistake where the editor would only be updated if the theme changed, not the color scheme alone.

Version 2020.1-1.0.3 of the plugin should hopefully fix this!
